# Go Releaser config file
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    id: "rmbl-build"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    # Build IDs to gather the binaries from.
    ids: ['rmbl-build', 'rmbl-server']

    # Templates of the Docker image names.
    image_templates:
    - "lhaig/rmbl-server:{{ .Tag }}"
    # - "lhaig/rmbl-server:v{{ .Major }}"
    # - "lhaig/rmbl-server:v{{ .Major }}.{{ .Minor }}"
    - "lhaig/rmbl-server:latest"

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    skip_push: true
    dockerfile: Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.maintainer='Lance Haig <lnhaig@gmail.com>'"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'